version: '3'
services:
  api:
    build: .
    ports:
      - "3005:3005"
    networks: 
      - backend
    depends_on:
      - postgres
    environment:
      DB_PWD: postgres
      DB_USER: postgres
      DB_NAME: backend-test
      DB_HOST: localhost
  postgres:
    image: postgres
    volumes:
      - cdp-db:/usr/src/db
    restart: always
    ports:
      - "5432:5432"
    networks: 
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
networks: 
  backend:
volumes:
  cdp-db: